/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stageplaatsenadmin;

import DAL.Bedrijf;
import DAL.DBFacade;
import java.util.List;

/**
 *
 * @author patrik
 */
public class BedrijfForm extends javax.swing.JFrame {

    private final DBFacade dbFacade;
    private List<Bedrijf> bedrijven;
    private Bedrijf geselecteerdBedrijf;
    
    /**
     * Creates new form BedrijfForm
     */
    public BedrijfForm() {
        initComponents();
        dbFacade = new DBFacade();
        this.refreshDataCache();
        this.refreshListbox();
    }

    private void refreshDataCache(){
        this.bedrijven = dbFacade.getAllBedrijven();
    }
    
    private void refreshListbox(){
        this.jListBedrijven.setListData(this.bedrijven.toArray());
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListBedrijven = new javax.swing.JList();

        setAlwaysOnTop(true);

        jListBedrijven.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListBedrijven);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 579, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jListBedrijven;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
