package stageplaatsenadmin;

import DAL.Bedrijf;
import DAL.DBFacade;
import DAL.Situeert;
import DAL.Specialisatie;
import DAL.Stageplaats;
import DAL.StudentStageplaats;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;

/**
 * Main form for managing the Stageplaatsen.
 * @author patrik
 */
public class OverzichtForm extends javax.swing.JFrame {

    /**
     * Creates new form OverzichtForm
     */
    
    private List<Stageplaats> stageplaatsen;
    private List<Specialisatie> specialisaties;
    private List<Situeert> SpecialisatieSitueert;
    private List<Bedrijf> bedrijven;
    private final DBFacade dbFacade;
    private Stageplaats geselecteerdeStageplaats;
    
    /**
     * Constructor
     */
    public OverzichtForm() {
        initComponents();
        dbFacade = new DBFacade();
        geselecteerdeStageplaats = null;
        specialisaties = null;
        SpecialisatieSitueert = null;
        bedrijven = null;
        this.refreshDataCache();
        loadStaticData();
        this.refreshListbox();
        enableButtons();

/*    
       private void btnOpslaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpslaanActionPerformed

        stageplaats.add(s);
        refreshListbox();
    }//GEN-LAST:event_btnOpslaanActionPerformed
*/  
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListStageplaatsen = new javax.swing.JList();
        jLabelGUIID = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jLabelGUIAanmaakdatum = new javax.swing.JLabel();
        jLabelAanmaakdatum = new javax.swing.JLabel();
        jLabelGUILaatsteWijziging = new javax.swing.JLabel();
        jLabellaatsteWijzing = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonNewStageplaats = new javax.swing.JButton();
        jButtonDeleteStageplaats = new javax.swing.JButton();
        jButtonSaveStageplaats = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabelGUITitel = new javax.swing.JLabel();
        jTextFieldTitel = new javax.swing.JTextField();
        jLabelGUIOmschrijving = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaOmschrijving = new javax.swing.JTextArea();
        jLabelGUIAantalPlaatsen = new javax.swing.JLabel();
        jSliderAantalPlaatsen = new javax.swing.JSlider();
        jLabelGUIPeriode = new javax.swing.JLabel();
        jTextFieldPeriode = new javax.swing.JTextField();
        jLabelGUIBegeleiding = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaBegeleiding = new javax.swing.JTextArea();
        jLabelGUIVereisteKennis = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaVereisteKennis = new javax.swing.JTextArea();
        jLabelGUIVoorzieningen = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaVoorzieningen = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabelGUISpecialisatie = new javax.swing.JLabel();
        jComboBoxSpecialisatie = new javax.swing.JComboBox<>();
        jLabelGUISitueert = new javax.swing.JLabel();
        jComboBoxSitueert = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabelGUIBedrijf = new javax.swing.JLabel();
        jTextFieldBedrijfsnaam = new javax.swing.JTextField();
        jLabelGUIContactpersoon = new javax.swing.JLabel();
        jTextFieldContactpersoon = new javax.swing.JTextField();
        jLabelGUIEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelGUIActiviteiten = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextAreaActiviteiten = new javax.swing.JTextArea();
        jLabelGUIAanwervend = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextAreaAanwervend = new javax.swing.JTextArea();
        jLabelGUIStraat = new javax.swing.JLabel();
        jTextFieldStraat = new javax.swing.JTextField();
        jLabelGUINummer = new javax.swing.JLabel();
        jTextFieldNummer = new javax.swing.JTextField();
        jLabelGUIPostcode = new javax.swing.JLabel();
        jTextFieldPostcode = new javax.swing.JTextField();
        jLabelGUIStad = new javax.swing.JLabel();
        jTextFieldStad = new javax.swing.JTextField();
        jLabelGUILand = new javax.swing.JLabel();
        jTextFieldLand = new javax.swing.JTextField();
        jLabelGUIAdres = new javax.swing.JLabel();
        jButtonBedrijfSelecteren = new javax.swing.JButton();
        jComboBoxGekendeBedrijven = new javax.swing.JComboBox();
        jButtonBeheerBedrijven = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jListStageplaatsen.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListStageplaatsen.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListStageplaatsenValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jListStageplaatsen);

        jLabelGUIID.setText("ID");

        jLabelID.setText("00000");

        jLabelGUIAanmaakdatum.setText("Aangemaakt op:");

        jLabelAanmaakdatum.setText("01/01/2018 - 19u59");

        jLabelGUILaatsteWijziging.setText("Laatste wijziging:");

        jLabellaatsteWijzing.setText("01/01/2018 - 19u59");

        jButtonNewStageplaats.setText("Nieuw");
        jButtonNewStageplaats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewStageplaatsActionPerformed(evt);
            }
        });

        jButtonDeleteStageplaats.setText("Wissen");
        jButtonDeleteStageplaats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteStageplaatsActionPerformed(evt);
            }
        });

        jButtonSaveStageplaats.setText("Opslaan");
        jButtonSaveStageplaats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveStageplaatsActionPerformed(evt);
            }
        });

        jLabelGUITitel.setText("Titel:");

        jLabelGUIOmschrijving.setText("Omschrijving");

        jTextAreaOmschrijving.setColumns(20);
        jTextAreaOmschrijving.setLineWrap(true);
        jTextAreaOmschrijving.setRows(5);
        jTextAreaOmschrijving.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextAreaOmschrijving);

        jLabelGUIAantalPlaatsen.setText("Aantal plaatsen");

        jSliderAantalPlaatsen.setMajorTickSpacing(5);
        jSliderAantalPlaatsen.setMaximum(50);
        jSliderAantalPlaatsen.setMinorTickSpacing(1);
        jSliderAantalPlaatsen.setPaintLabels(true);
        jSliderAantalPlaatsen.setPaintTicks(true);
        jSliderAantalPlaatsen.setSnapToTicks(true);
        jSliderAantalPlaatsen.setToolTipText("");
        jSliderAantalPlaatsen.setValue(1);

        jLabelGUIPeriode.setText("Periode");

        jLabelGUIBegeleiding.setText("Voorziene begeleiding");

        jTextAreaBegeleiding.setColumns(20);
        jTextAreaBegeleiding.setRows(5);
        jScrollPane3.setViewportView(jTextAreaBegeleiding);

        jLabelGUIVereisteKennis.setText("Extra vereiste kennis");

        jTextAreaVereisteKennis.setColumns(20);
        jTextAreaVereisteKennis.setRows(5);
        jScrollPane4.setViewportView(jTextAreaVereisteKennis);

        jLabelGUIVoorzieningen.setText("Voorzieningen");

        jTextAreaVoorzieningen.setColumns(20);
        jTextAreaVoorzieningen.setRows(5);
        jScrollPane5.setViewportView(jTextAreaVoorzieningen);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jSliderAantalPlaatsen, javax.swing.GroupLayout.DEFAULT_SIZE, 1216, Short.MAX_VALUE)
                    .addComponent(jTextFieldPeriode)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldTitel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabelGUIOmschrijving))
                                    .addComponent(jLabelGUIAantalPlaatsen)
                                    .addComponent(jLabelGUIPeriode)
                                    .addComponent(jLabelGUITitel)
                                    .addComponent(jLabelGUIBegeleiding)
                                    .addComponent(jLabelGUIVereisteKennis)
                                    .addComponent(jLabelGUIVoorzieningen))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelGUITitel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTitel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelGUIOmschrijving)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelGUIAantalPlaatsen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSliderAantalPlaatsen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelGUIPeriode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPeriode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelGUIBegeleiding)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelGUIVereisteKennis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelGUIVoorzieningen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Stageplaats", jPanel1);

        jLabelGUISpecialisatie.setText("Specialisatie:");

        jComboBoxSpecialisatie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxSpecialisatie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSpecialisatieActionPerformed(evt);
            }
        });

        jLabelGUISitueert.setText("Situeert in");

        jComboBoxSitueert.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxSitueert, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxSpecialisatie, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelGUISpecialisatie)
                            .addComponent(jLabelGUISitueert))
                        .addGap(0, 985, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelGUISpecialisatie)
                .addGap(0, 0, 0)
                .addComponent(jComboBoxSpecialisatie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelGUISitueert)
                .addGap(0, 0, 0)
                .addComponent(jComboBoxSitueert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(494, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Classificatie", jPanel2);

        jLabelGUIBedrijf.setText("Bedrijf:");

        jLabelGUIContactpersoon.setText("Contactpersoon");

        jLabelGUIEmail.setText("Email");

        jLabelGUIActiviteiten.setText("Activiteiten");

        jTextAreaActiviteiten.setColumns(20);
        jTextAreaActiviteiten.setRows(5);
        jScrollPane6.setViewportView(jTextAreaActiviteiten);

        jLabelGUIAanwervend.setText("Aanwervend:");

        jTextAreaAanwervend.setColumns(20);
        jTextAreaAanwervend.setRows(5);
        jScrollPane7.setViewportView(jTextAreaAanwervend);

        jLabelGUIStraat.setText("Straat");

        jLabelGUINummer.setText("Nummer");

        jLabelGUIPostcode.setText("Postcode");

        jLabelGUIStad.setText("Stad");

        jLabelGUILand.setText("Land");

        jLabelGUIAdres.setText("Adres:");

        jButtonBedrijfSelecteren.setText("Selecteren");
        jButtonBedrijfSelecteren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBedrijfSelecterenActionPerformed(evt);
            }
        });

        jComboBoxGekendeBedrijven.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonBeheerBedrijven.setText("Beheer Bedrijven");
        jButtonBeheerBedrijven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBeheerBedrijvenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldContactpersoon, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldBedrijfsnaam)
                            .addComponent(jTextFieldEmail)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 1206, Short.MAX_VALUE)
                            .addComponent(jScrollPane7)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelGUIBedrijf)
                                    .addComponent(jLabelGUIContactpersoon)
                                    .addComponent(jLabelGUIEmail)
                                    .addComponent(jLabelGUIActiviteiten)
                                    .addComponent(jLabelGUIAanwervend)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabelGUIStraat)
                                        .addGap(474, 474, 474)
                                        .addComponent(jLabelGUINummer))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jTextFieldStraat, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldNummer, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabelGUIAdres)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jTextFieldPostcode, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldStad, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabelGUIPostcode)
                                                .addGap(102, 102, 102)
                                                .addComponent(jLabelGUIStad)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelGUILand)
                                            .addComponent(jTextFieldLand, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jComboBoxGekendeBedrijven, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBedrijfSelecteren)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBeheerBedrijven)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxGekendeBedrijven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBedrijfSelecteren)
                    .addComponent(jButtonBeheerBedrijven))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelGUIBedrijf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldBedrijfsnaam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelGUIContactpersoon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldContactpersoon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelGUIEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelGUIActiviteiten)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelGUIAanwervend)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelGUIAdres)
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGUIStraat)
                    .addComponent(jLabelGUINummer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldStraat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGUIStad)
                    .addComponent(jLabelGUIPostcode)
                    .addComponent(jLabelGUILand))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldStad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldPostcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Bedrijf", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelGUIID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelGUILaatsteWijziging)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabellaatsteWijzing)
                                .addGap(26, 26, 26)
                                .addComponent(jLabelGUIAanmaakdatum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelAanmaakdatum))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(491, 491, 491)
                                .addComponent(jButtonDeleteStageplaats)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonNewStageplaats)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSaveStageplaats)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addComponent(jSeparator1)
                    .addComponent(jTabbedPane1)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonNewStageplaats)
                            .addComponent(jButtonSaveStageplaats)
                            .addComponent(jButtonDeleteStageplaats))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelGUIID)
                                .addComponent(jLabelID))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelGUIAanmaakdatum)
                                .addComponent(jLabelAanmaakdatum)
                                .addComponent(jLabelGUILaatsteWijziging)
                                .addComponent(jLabellaatsteWijzing)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     /**
     * Displays the selected Stageplaats.
     */
    private void jListStageplaatsenValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListStageplaatsenValueChanged
        Stageplaats s = (Stageplaats)jListStageplaatsen.getSelectedValue();
        if (s != null){ this.geselecteerdeStageplaats = s; }
        ClearDisplayedStageplaats();
        refreshDisplayedStageplaats();
        enableButtons();
    }//GEN-LAST:event_jListStageplaatsenValueChanged

     /**
     * Fills the Situeert-combobox with the Situeert related to the selected Specialisatie.
     */
    private void jComboBoxSpecialisatieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSpecialisatieActionPerformed

        this.SpecialisatieSitueert = this.dbFacade.getAllSitueertOfSpecialisatieID(((Specialisatie)this.jComboBoxSpecialisatie.getSelectedItem()).getId());
        this.jComboBoxSitueert.setModel(new DefaultComboBoxModel(this.SpecialisatieSitueert.toArray()));
    }//GEN-LAST:event_jComboBoxSpecialisatieActionPerformed

     /**
     * Stores the displayed Stageplaats in the database.
     */
    private void jButtonSaveStageplaatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveStageplaatsActionPerformed

        storeDisplayedStageplaats();
      
        this.dbFacade.persist((this.geselecteerdeStageplaats));
        refreshDataCache();
        refreshListbox();
    }//GEN-LAST:event_jButtonSaveStageplaatsActionPerformed

     /**
     * Creates a new Stageplaats, and displays it. Requires to be stored afterwards.
     */
    private void jButtonNewStageplaatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewStageplaatsActionPerformed

        this.geselecteerdeStageplaats = new Stageplaats();
        this.geselecteerdeStageplaats.setSitueertID((Situeert)this.jComboBoxSitueert.getSelectedItem());
        this.geselecteerdeStageplaats.getSitueertID().setSpecialisatieID((Specialisatie)this.jComboBoxSpecialisatie.getSelectedItem());
        this.geselecteerdeStageplaats.setBedrijfID(null);
        this.geselecteerdeStageplaats.setAanmaakDatum(new Date());
        this.geselecteerdeStageplaats.setLaatsteWijziging(new Date());
        this.geselecteerdeStageplaats.setStudentStageplaatsList(new ArrayList<StudentStageplaats>());
        refreshDataCache();
        ClearDisplayedStageplaats();
        refreshDisplayedStageplaats();
        enableButtons();
    }//GEN-LAST:event_jButtonNewStageplaatsActionPerformed

     /**
     * Deletes the selected Stageplaats.
     */
    private void jButtonDeleteStageplaatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteStageplaatsActionPerformed

        Stageplaats s = (Stageplaats)jListStageplaatsen.getSelectedValue();
        if (s != null){
            int index = this.jListStageplaatsen.getSelectedIndex();
            Stageplaats sFromDB = this.dbFacade.getStageplaatsByID(s.getId());
            if (sFromDB != null){
                this.dbFacade.remove(sFromDB);
                refreshDataCache();
                refreshListbox();
                if (index > 0) index--;
                this.jListStageplaatsen.setSelectedIndex(index);
            }
        }
        enableButtons();
    }//GEN-LAST:event_jButtonDeleteStageplaatsActionPerformed


     /**
     * Adds the selected Bedrijf to the displayed Stageplaats. Requires to be stored afterwards.
     */
    private void jButtonBedrijfSelecterenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBedrijfSelecterenActionPerformed

        Bedrijf geselecteerdBedrijf = (Bedrijf)this.jComboBoxGekendeBedrijven.getSelectedItem();
        if (geselecteerdBedrijf != null && geselecteerdBedrijf.getId() != null){
            this.geselecteerdeStageplaats.setBedrijfID(this.dbFacade.getBedrijfByID(geselecteerdBedrijf.getId()));
            displayBedrijf();
        }
        this.enableButtons();
    }//GEN-LAST:event_jButtonBedrijfSelecterenActionPerformed

    
    private BedrijfForm bedrijfForm;
    
     /**
     * Opens the BedrijfForm to manage the Bedrijven  in the database.
     */
    private void jButtonBeheerBedrijvenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBeheerBedrijvenActionPerformed

        if (bedrijfForm == null) {
            bedrijfForm = new BedrijfForm(this, this.dbFacade);
            bedrijfForm.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        }
        bedrijfForm.setVisible(true);
        
    }//GEN-LAST:event_jButtonBeheerBedrijvenActionPerformed

     /**
     * Loads all constant values from the database.
     */
    private void loadStaticData(){
        this.specialisaties = this.dbFacade.getAllSpecialisaties();
        this.jComboBoxSpecialisatie.setModel(new DefaultComboBoxModel(this.specialisaties.toArray()));
        this.SpecialisatieSitueert = this.dbFacade.getAllSitueert();
        this.jComboBoxSitueert.setModel(new DefaultComboBoxModel(this.SpecialisatieSitueert.toArray()));
    }
    
     /**
     * Reloads the list of stageplaatsen and Bedrijven from the database.
     */
    private void refreshDataCache(){
        this.stageplaatsen = dbFacade.getAllStageplaatsen();
        this.bedrijven = dbFacade.getAllBedrijven();
    }
    
     /**
     * Reloads the listboc/combobox of stageplaatsen and Bedrijven from the lists.
     */
    private void refreshListbox(){
        this.jListStageplaatsen.setListData(this.stageplaatsen.toArray());
        this.jComboBoxGekendeBedrijven.setModel(new DefaultComboBoxModel(this.bedrijven.toArray()));
        
    }
    
    /**
     * Force a full reload of the stageplaats en Bedrijf lists and listbox/combox. 
     */
    public void reloadDatasources(){
        refreshDataCache();
        refreshListbox();
        
        if (this.geselecteerdeStageplaats != null)
        { 
            this.geselecteerdeStageplaats =  this.dbFacade.getStageplaatsByID(this.geselecteerdeStageplaats.getId());
        }
        refreshDisplayedStageplaats();
    }
    
     /**
     * Reloads the displayed stageplaats.
     */
    private void refreshDisplayedStageplaats(){
        if (this.geselecteerdeStageplaats != null){
            if (this.geselecteerdeStageplaats.getId() != null){
                this.jLabelID.setText(this.geselecteerdeStageplaats.getId().toString());
            }
            this.jTextFieldTitel.setText(this.geselecteerdeStageplaats.getTitel());
            this.jTextAreaOmschrijving.setText(this.geselecteerdeStageplaats.getOmschrijving());
            this.jSliderAantalPlaatsen.setValue(this.geselecteerdeStageplaats.getAantalPlaatsen());
            this.jTextFieldPeriode.setText(this.geselecteerdeStageplaats.getPeriode());
            this.jTextAreaBegeleiding.setText((this.geselecteerdeStageplaats.getBegeleiding()));
            this.jTextAreaVereisteKennis.setText(this.geselecteerdeStageplaats.getExtraKennisVereist());
            this.jTextAreaVoorzieningen.setText(this.geselecteerdeStageplaats.getVoorzieningen());
            this.jComboBoxSpecialisatie.setSelectedItem(this.geselecteerdeStageplaats.getSitueertID().getSpecialisatieID());
            this.SpecialisatieSitueert = this.dbFacade.getAllSitueertOfSpecialisatieID(this.geselecteerdeStageplaats.getSitueertID().getSpecialisatieID().getId());
            this.jComboBoxSitueert.setModel(new DefaultComboBoxModel(this.SpecialisatieSitueert.toArray()));
            
            this.jComboBoxSitueert.setSelectedItem(this.geselecteerdeStageplaats.getSitueertID());
            
            // Bedrijf
            displayBedrijf();
            
            SimpleDateFormat dateformat = new SimpleDateFormat("dd-MM-yyyy '-' HH:mm:ss");
            this.jLabelAanmaakdatum.setText(dateformat.format(this.geselecteerdeStageplaats.getAanmaakDatum()));
            this.jLabellaatsteWijzing.setText(dateformat.format(this.geselecteerdeStageplaats.getLaatsteWijziging()));
        }
    }

     /**
     * Store the content of the form controls in the fields of the selected Stageplaats.
     */
    private void storeDisplayedStageplaats(){
        if (this.geselecteerdeStageplaats == null){
            this.geselecteerdeStageplaats = new Stageplaats();
        }
        
        this.geselecteerdeStageplaats.setTitel(this.jTextFieldTitel.getText());
        this.geselecteerdeStageplaats.setOmschrijving(this.jTextAreaOmschrijving.getText());
        this.geselecteerdeStageplaats.setAantalPlaatsen(this.jSliderAantalPlaatsen.getValue());
        this.geselecteerdeStageplaats.setPeriode(this.jTextFieldPeriode.getText());
        this.geselecteerdeStageplaats.setBegeleiding(this.jTextAreaBegeleiding.getText());
        this.geselecteerdeStageplaats.setExtraKennisVereist(this.jTextAreaVereisteKennis.getText());
        this.geselecteerdeStageplaats.setVoorzieningen(this.jTextAreaVoorzieningen.getText());
        this.geselecteerdeStageplaats.setSitueertID((Situeert)this.jComboBoxSitueert.getSelectedItem());
        this.geselecteerdeStageplaats.getSitueertID().setSpecialisatieID((Specialisatie)this.jComboBoxSpecialisatie.getSelectedItem());
            
    }
    
     /**
     * Displays the Bedrijf of the selected Stageplaats.
     */
    private void displayBedrijf(){
            if (this.geselecteerdeStageplaats.getBedrijfID() != null){
            this.jTextFieldBedrijfsnaam.setText(this.geselecteerdeStageplaats.getBedrijfID().getNaam());
            this.jTextFieldContactpersoon.setText(this.geselecteerdeStageplaats.getBedrijfID().getContactNaam());
            this.jTextFieldEmail.setText(this.geselecteerdeStageplaats.getBedrijfID().getContactEmail());
            this.jTextAreaActiviteiten.setText(this.geselecteerdeStageplaats.getBedrijfID().getActiviteiten());
            this.jTextAreaAanwervend.setText(this.geselecteerdeStageplaats.getBedrijfID().getAanwervend());
            
            this.jTextFieldStraat.setText(this.geselecteerdeStageplaats.getBedrijfID().getStraat());
            this.jTextFieldNummer.setText(this.geselecteerdeStageplaats.getBedrijfID().getNummer());
            this.jTextFieldPostcode.setText(this.geselecteerdeStageplaats.getBedrijfID().getPostcode());
            this.jTextFieldStad.setText(this.geselecteerdeStageplaats.getBedrijfID().getStad());
            this.jTextFieldLand.setText(this.geselecteerdeStageplaats.getBedrijfID().getLand());
            }
    }
    
    
    
    
    /**
     * Clears the form controls.
     */
    private void ClearDisplayedStageplaats(){
        
            this.jLabelID.setText("");
            
            this.jTextFieldTitel.setText("");
            this.jTextAreaOmschrijving.setText("");
            this.jSliderAantalPlaatsen.setValue(1);
            this.jTextFieldPeriode.setText("");
            this.jTextAreaBegeleiding.setText("");
            this.jTextAreaVereisteKennis.setText("");
            this.jTextAreaVoorzieningen.setText("");

            // Bedrijf
            this.jTextFieldBedrijfsnaam.setText("");
            this.jTextFieldContactpersoon.setText("");
            this.jTextFieldEmail.setText("");
            this.jTextAreaActiviteiten.setText("");
            this.jTextAreaAanwervend.setText("");
            
            this.jTextFieldStraat.setText("");
            this.jTextFieldNummer.setText("");
            this.jTextFieldPostcode.setText("");
            this.jTextFieldStad.setText("");
            this.jTextFieldLand.setText("");
            
            this.jLabelAanmaakdatum.setText("");
            this.jLabellaatsteWijzing.setText("");
    }
    
     /**
     * Enables the buttons when all required data is selected.
     */
    private void enableButtons(){
        
        if (this.geselecteerdeStageplaats != null && this.geselecteerdeStageplaats.getBedrijfID() != null){
            this.jButtonSaveStageplaats.setEnabled(true);
            this.jButtonDeleteStageplaats.setEnabled(true);

        }
        else{
            this.jButtonSaveStageplaats.setEnabled(false);
            this.jButtonDeleteStageplaats.setEnabled(false);
        }
            if (this.jComboBoxGekendeBedrijven.getSelectedItem() != null){
                this.jButtonBedrijfSelecteren.setEnabled(true);
            }
            else {
                this.jButtonBedrijfSelecteren.setEnabled(false);
            }
        
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OverzichtForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OverzichtForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OverzichtForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OverzichtForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OverzichtForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBedrijfSelecteren;
    private javax.swing.JButton jButtonBeheerBedrijven;
    private javax.swing.JButton jButtonDeleteStageplaats;
    private javax.swing.JButton jButtonNewStageplaats;
    private javax.swing.JButton jButtonSaveStageplaats;
    private javax.swing.JComboBox jComboBoxGekendeBedrijven;
    private javax.swing.JComboBox<String> jComboBoxSitueert;
    private javax.swing.JComboBox<String> jComboBoxSpecialisatie;
    private javax.swing.JLabel jLabelAanmaakdatum;
    private javax.swing.JLabel jLabelGUIAanmaakdatum;
    private javax.swing.JLabel jLabelGUIAantalPlaatsen;
    private javax.swing.JLabel jLabelGUIAanwervend;
    private javax.swing.JLabel jLabelGUIActiviteiten;
    private javax.swing.JLabel jLabelGUIAdres;
    private javax.swing.JLabel jLabelGUIBedrijf;
    private javax.swing.JLabel jLabelGUIBegeleiding;
    private javax.swing.JLabel jLabelGUIContactpersoon;
    private javax.swing.JLabel jLabelGUIEmail;
    private javax.swing.JLabel jLabelGUIID;
    private javax.swing.JLabel jLabelGUILaatsteWijziging;
    private javax.swing.JLabel jLabelGUILand;
    private javax.swing.JLabel jLabelGUINummer;
    private javax.swing.JLabel jLabelGUIOmschrijving;
    private javax.swing.JLabel jLabelGUIPeriode;
    private javax.swing.JLabel jLabelGUIPostcode;
    private javax.swing.JLabel jLabelGUISitueert;
    private javax.swing.JLabel jLabelGUISpecialisatie;
    private javax.swing.JLabel jLabelGUIStad;
    private javax.swing.JLabel jLabelGUIStraat;
    private javax.swing.JLabel jLabelGUITitel;
    private javax.swing.JLabel jLabelGUIVereisteKennis;
    private javax.swing.JLabel jLabelGUIVoorzieningen;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabellaatsteWijzing;
    private javax.swing.JList jListStageplaatsen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSlider jSliderAantalPlaatsen;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextAreaAanwervend;
    private javax.swing.JTextArea jTextAreaActiviteiten;
    private javax.swing.JTextArea jTextAreaBegeleiding;
    private javax.swing.JTextArea jTextAreaOmschrijving;
    private javax.swing.JTextArea jTextAreaVereisteKennis;
    private javax.swing.JTextArea jTextAreaVoorzieningen;
    private javax.swing.JTextField jTextFieldBedrijfsnaam;
    private javax.swing.JTextField jTextFieldContactpersoon;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldLand;
    private javax.swing.JTextField jTextFieldNummer;
    private javax.swing.JTextField jTextFieldPeriode;
    private javax.swing.JTextField jTextFieldPostcode;
    private javax.swing.JTextField jTextFieldStad;
    private javax.swing.JTextField jTextFieldStraat;
    private javax.swing.JTextField jTextFieldTitel;
    // End of variables declaration//GEN-END:variables
}
