/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stageplaatsenadmin;

import DAL.DBFacade;
import DAL.Situeert;
import DAL.Specialisatie;
import DAL.Stageplaats;
import DAL.StudentStageplaats;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author patrik
 */
public class OverzichtForm extends javax.swing.JFrame {

    /**
     * Creates new form OverzichtForm
     */
    
    private List<Stageplaats> stageplaatsen;
    private List<Specialisatie> specialisaties;
    private List<Situeert> SpecialisatieSitueert;
    private DBFacade dbFacade;
    private Stageplaats geselecteerdeStageplaats;
    
    
    public OverzichtForm() {
        initComponents();
        dbFacade = new DBFacade();
        geselecteerdeStageplaats = null;
        specialisaties = null;
        SpecialisatieSitueert = null;
        this.refreshDataCache();
        loadStaticData();
        this.refreshListbox();

/*
        example code listbox:
        
        
       private void btnOpslaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpslaanActionPerformed
        // TODO add your handling code here:
        
        Stageplaats s = new Stageplaats();
        s.setEmail(txtEmail.getText());
        s.setGeboortejaar(Integer.parseInt(txtGeboortejaar.getText()));
        s.setGsm(txtGsm.getText());
        s.setNaam(txtNaam.getText());
        
        stageplaatsen.add(s);
        refreshListbox();
        
    }//GEN-LAST:event_btnOpslaanActionPerformed

    private void btnVerwijderenActionPerformed(java.awt.event.ActionEvent evt) {                                               
        
        Stageplaats s = (Stageplaats)jList1.getSelectedValue();
        Stageplaatsen.remove(s);
        refreshListbox();
        
        
    }                                                   
               

        
*/  
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jListStageplaatsen = new javax.swing.JList();
        jLabelGUIID = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jLabelGUITitel = new javax.swing.JLabel();
        jTextFieldTitel = new javax.swing.JTextField();
        jLabelGUIOmschrijving = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaOmschrijving = new javax.swing.JTextArea();
        jLabelGUIAantalPlaatsen = new javax.swing.JLabel();
        jSliderAantalPlaatsen = new javax.swing.JSlider();
        jLabelGUIPeriode = new javax.swing.JLabel();
        jTextFieldPeriode = new javax.swing.JTextField();
        jLabelGUIBegeleiding = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaBegeleiding = new javax.swing.JTextArea();
        jLabelGUIVereisteKennis = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaVereisteKennis = new javax.swing.JTextArea();
        jLabelGUIVoorzieningen = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaVoorzieningen = new javax.swing.JTextArea();
        jLabelGUIBedrijf = new javax.swing.JLabel();
        jTextFieldBedrijfsnaam = new javax.swing.JTextField();
        jButtonChangeBedrijf = new javax.swing.JButton();
        jLabelGUISpecialisatie = new javax.swing.JLabel();
        jComboBoxSpecialisatie = new javax.swing.JComboBox<>();
        jLabelGUISitueert = new javax.swing.JLabel();
        jComboBoxSitueert = new javax.swing.JComboBox<>();
        jLabelGUIAanmaakdatum = new javax.swing.JLabel();
        jLabelAanmaakdatum = new javax.swing.JLabel();
        jLabelGUILaatsteWijziging = new javax.swing.JLabel();
        jLabellaatsteWijzing = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonNewStageplaats = new javax.swing.JButton();
        jButtonDeleteStageplaats = new javax.swing.JButton();
        jButtonSaveStageplaats = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jListStageplaatsen.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListStageplaatsen.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListStageplaatsenValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jListStageplaatsen);

        jLabelGUIID.setText("ID");

        jLabelID.setText("00000");

        jLabelGUITitel.setText("Titel:");

        jLabelGUIOmschrijving.setText("Omschrijving");

        jTextAreaOmschrijving.setColumns(20);
        jTextAreaOmschrijving.setLineWrap(true);
        jTextAreaOmschrijving.setRows(5);
        jTextAreaOmschrijving.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextAreaOmschrijving);

        jLabelGUIAantalPlaatsen.setText("Aantal plaatsen");

        jSliderAantalPlaatsen.setMajorTickSpacing(5);
        jSliderAantalPlaatsen.setMaximum(50);
        jSliderAantalPlaatsen.setMinorTickSpacing(1);
        jSliderAantalPlaatsen.setPaintLabels(true);
        jSliderAantalPlaatsen.setPaintTicks(true);
        jSliderAantalPlaatsen.setSnapToTicks(true);
        jSliderAantalPlaatsen.setToolTipText("");
        jSliderAantalPlaatsen.setValue(1);

        jLabelGUIPeriode.setText("Periode");

        jLabelGUIBegeleiding.setText("Voorziene begeleiding");

        jTextAreaBegeleiding.setColumns(20);
        jTextAreaBegeleiding.setRows(5);
        jScrollPane3.setViewportView(jTextAreaBegeleiding);

        jLabelGUIVereisteKennis.setText("Extra vereiste kennis");

        jTextAreaVereisteKennis.setColumns(20);
        jTextAreaVereisteKennis.setRows(5);
        jScrollPane4.setViewportView(jTextAreaVereisteKennis);

        jLabelGUIVoorzieningen.setText("Voorzieningen");

        jTextAreaVoorzieningen.setColumns(20);
        jTextAreaVoorzieningen.setRows(5);
        jScrollPane5.setViewportView(jTextAreaVoorzieningen);

        jLabelGUIBedrijf.setText("Bedrijf:");

        jButtonChangeBedrijf.setText("Wijzigen");
        jButtonChangeBedrijf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangeBedrijfActionPerformed(evt);
            }
        });

        jLabelGUISpecialisatie.setText("Specialisatie:");

        jComboBoxSpecialisatie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxSpecialisatie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSpecialisatieActionPerformed(evt);
            }
        });

        jLabelGUISitueert.setText("Situeert in");

        jComboBoxSitueert.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelGUIAanmaakdatum.setText("Aangemaakt op:");

        jLabelAanmaakdatum.setText("01/01/2018 - 19u59");

        jLabelGUILaatsteWijziging.setText("Laatste wijziging:");

        jLabellaatsteWijzing.setText("01/01/2018 - 19u59");

        jButtonNewStageplaats.setText("Nieuw");
        jButtonNewStageplaats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewStageplaatsActionPerformed(evt);
            }
        });

        jButtonDeleteStageplaats.setText("Wissen");
        jButtonDeleteStageplaats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteStageplaatsActionPerformed(evt);
            }
        });

        jButtonSaveStageplaats.setText("Opslaan");
        jButtonSaveStageplaats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveStageplaatsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelGUIAantalPlaatsen)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelGUIID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelGUILaatsteWijziging)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabellaatsteWijzing)
                                .addGap(26, 26, 26)
                                .addComponent(jLabelGUIAanmaakdatum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelAanmaakdatum))
                            .addComponent(jScrollPane1)
                            .addComponent(jTextFieldTitel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelGUIBedrijf)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jTextFieldBedrijfsnaam))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonChangeBedrijf))
                            .addComponent(jSliderAantalPlaatsen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldPeriode)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane4)
                            .addComponent(jScrollPane5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxSpecialisatie, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelGUIOmschrijving)
                                    .addComponent(jLabelGUITitel)
                                    .addComponent(jLabelGUIPeriode)
                                    .addComponent(jLabelGUIBegeleiding)
                                    .addComponent(jLabelGUIVereisteKennis)
                                    .addComponent(jLabelGUIVoorzieningen)
                                    .addComponent(jLabelGUISpecialisatie))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxSitueert, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelGUISitueert)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(486, 486, 486)
                                .addComponent(jButtonDeleteStageplaats)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonNewStageplaats)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSaveStageplaats)
                                .addGap(0, 591, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addComponent(jSeparator1)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabelGUITitel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTitel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelGUIOmschrijving)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelGUIAantalPlaatsen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSliderAantalPlaatsen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelGUIPeriode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPeriode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelGUIBegeleiding)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelGUIVereisteKennis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelGUIVoorzieningen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelGUIBedrijf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldBedrijfsnaam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonChangeBedrijf))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelGUISpecialisatie)
                            .addComponent(jLabelGUISitueert))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxSpecialisatie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxSitueert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonNewStageplaats)
                            .addComponent(jButtonSaveStageplaats)
                            .addComponent(jButtonDeleteStageplaats))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelGUIID)
                                .addComponent(jLabelID))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelGUIAanmaakdatum)
                                .addComponent(jLabelAanmaakdatum)
                                .addComponent(jLabelGUILaatsteWijziging)
                                .addComponent(jLabellaatsteWijzing)))
                        .addContainerGap(18, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jListStageplaatsenValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListStageplaatsenValueChanged
        Stageplaats s = (Stageplaats)jListStageplaatsen.getSelectedValue();
        if (s != null){ this.geselecteerdeStageplaats = s; }
        refreshDisplayedStageplaats();
    }//GEN-LAST:event_jListStageplaatsenValueChanged

    private void jButtonChangeBedrijfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangeBedrijfActionPerformed
        

    // TODO Toon form om bedrijf te wijzigen


    }//GEN-LAST:event_jButtonChangeBedrijfActionPerformed

    private void jComboBoxSpecialisatieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSpecialisatieActionPerformed
        // TODO add your handling code here:
        this.SpecialisatieSitueert = this.dbFacade.getAllSitueertOfSpecialisatieID(((Specialisatie)this.jComboBoxSpecialisatie.getSelectedItem()).getId());
            //    this.geselecteerdeStageplaats.getSitueertID().getSpecialisatieID().getId());
        this.jComboBoxSitueert.setModel(new DefaultComboBoxModel(this.SpecialisatieSitueert.toArray()));
    }//GEN-LAST:event_jComboBoxSpecialisatieActionPerformed

    private void jButtonSaveStageplaatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveStageplaatsActionPerformed
        // TODO add your handling code here:
        
        storeDisplayedStageplaats();
        this.geselecteerdeStageplaats.setLaatsteWijziging(new Date());
        this.dbFacade.persist((this.geselecteerdeStageplaats));
        refreshDataCache();
        refreshListbox();
    }//GEN-LAST:event_jButtonSaveStageplaatsActionPerformed

    private void jButtonNewStageplaatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewStageplaatsActionPerformed
        // TODO add your handling code here:
        
        this.geselecteerdeStageplaats = new Stageplaats();
        this.geselecteerdeStageplaats.setSitueertID((Situeert)this.jComboBoxSitueert.getSelectedItem());
        this.geselecteerdeStageplaats.getSitueertID().setSpecialisatieID((Specialisatie)this.jComboBoxSpecialisatie.getSelectedItem());
        this.geselecteerdeStageplaats.setBedrijfID(this.dbFacade.getBedrijfByID(1));
        this.geselecteerdeStageplaats.setAanmaakDatum(new Date());
        this.geselecteerdeStageplaats.setLaatsteWijziging(new Date());
        this.geselecteerdeStageplaats.setStudentStageplaatsList(new ArrayList<StudentStageplaats>());
        refreshDataCache();
        refreshDisplayedStageplaats();
        
    }//GEN-LAST:event_jButtonNewStageplaatsActionPerformed

    private void jButtonDeleteStageplaatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteStageplaatsActionPerformed
        // TODO add your handling code here:
        
        Stageplaats s = (Stageplaats)jListStageplaatsen.getSelectedValue();
        int index = this.jListStageplaatsen.getSelectedIndex();
        this.dbFacade.removeStageplaats((s));
        refreshDataCache();
        refreshListbox();
        if (index > 0) index--;
        this.jListStageplaatsen.setSelectedIndex(index);
        
        
    }//GEN-LAST:event_jButtonDeleteStageplaatsActionPerformed

    private void loadStaticData(){
        this.specialisaties = this.dbFacade.getAllSpecialisaties();
        this.jComboBoxSpecialisatie.setModel(new DefaultComboBoxModel(this.specialisaties.toArray()));
        this.SpecialisatieSitueert = this.dbFacade.getAllSitueert();
        this.jComboBoxSitueert.setModel(new DefaultComboBoxModel(this.SpecialisatieSitueert.toArray()));
    }
    
    
    private void refreshDataCache(){
        this.stageplaatsen = dbFacade.getAllStageplaatsen();
    }
    
    private void refreshListbox(){
        this.jListStageplaatsen.setListData(this.stageplaatsen.toArray());
    }
    
    private void refreshDisplayedStageplaats(){
        if (this.geselecteerdeStageplaats != null){
            if (this.geselecteerdeStageplaats.getId() != null){
                this.jLabelID.setText(this.geselecteerdeStageplaats.getId().toString());
            }
            this.jTextFieldTitel.setText(this.geselecteerdeStageplaats.getTitel());
            this.jTextAreaOmschrijving.setText(this.geselecteerdeStageplaats.getOmschrijving());
            this.jSliderAantalPlaatsen.setValue(this.geselecteerdeStageplaats.getAantalPlaatsen());
            this.jTextFieldPeriode.setText(this.geselecteerdeStageplaats.getPeriode());
            this.jTextAreaBegeleiding.setText((this.geselecteerdeStageplaats.getBegeleiding()));
            this.jTextAreaVereisteKennis.setText(this.geselecteerdeStageplaats.getExtraKennisVereist());
            this.jTextAreaVoorzieningen.setText(this.geselecteerdeStageplaats.getVoorzieningen());
            this.jTextFieldBedrijfsnaam.setText(this.geselecteerdeStageplaats.getBedrijfID().getNaam());
            this.jComboBoxSpecialisatie.setSelectedItem(this.geselecteerdeStageplaats.getSitueertID().getSpecialisatieID());
            this.SpecialisatieSitueert = this.dbFacade.getAllSitueertOfSpecialisatieID(this.geselecteerdeStageplaats.getSitueertID().getSpecialisatieID().getId());
            this.jComboBoxSitueert.setModel(new DefaultComboBoxModel(this.SpecialisatieSitueert.toArray()));
            
            this.jComboBoxSitueert.setSelectedItem(this.geselecteerdeStageplaats.getSitueertID());
            
            SimpleDateFormat dateformat = new SimpleDateFormat("dd-MM-yyyy '-' HH:mm:ss");
            this.jLabelAanmaakdatum.setText(dateformat.format(this.geselecteerdeStageplaats.getAanmaakDatum()));
            this.jLabellaatsteWijzing.setText(dateformat.format(this.geselecteerdeStageplaats.getLaatsteWijziging()));
        }
    }
    // TODO make inverse method (from refreshDisplayedStageplaats) 
    // (fields to Stageplaatsobject.
    
    private void storeDisplayedStageplaats(){
        if (this.geselecteerdeStageplaats == null){
            this.geselecteerdeStageplaats = new Stageplaats();
        }
        
        this.geselecteerdeStageplaats.setTitel(this.jTextFieldTitel.getText());
        this.geselecteerdeStageplaats.setOmschrijving(this.jTextAreaOmschrijving.getText());
        this.geselecteerdeStageplaats.setAantalPlaatsen(this.jSliderAantalPlaatsen.getValue());
        this.geselecteerdeStageplaats.setPeriode(this.jTextFieldPeriode.getText());
        this.geselecteerdeStageplaats.setBegeleiding(this.jTextAreaBegeleiding.getText());
        this.geselecteerdeStageplaats.setExtraKennisVereist(this.jTextAreaVereisteKennis.getText());
        this.geselecteerdeStageplaats.setVoorzieningen(this.jTextAreaVoorzieningen.getText());
        this.geselecteerdeStageplaats.setSitueertID((Situeert)this.jComboBoxSitueert.getSelectedItem());
        this.geselecteerdeStageplaats.getSitueertID().setSpecialisatieID((Specialisatie)this.jComboBoxSpecialisatie.getSelectedItem());
            
        
            
        //    this.jTextFieldBedrijfsnaam.setText(this.geselecteerdeStageplaats.getBedrijfID().getNaam());

            
         //   SimpleDateFormat dateformat = new SimpleDateFormat("dd-MM-yyyy '-' HH:mm:ss");
         //   this.jLabelAanmaakdatum.setText(dateformat.format(this.geselecteerdeStageplaats.getAanmaakDatum()));
         //   this.jLabellaatsteWijzing.setText(dateformat.format(this.geselecteerdeStageplaats.getLaatsteWijziging()));

    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OverzichtForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OverzichtForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OverzichtForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OverzichtForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OverzichtForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonChangeBedrijf;
    private javax.swing.JButton jButtonDeleteStageplaats;
    private javax.swing.JButton jButtonNewStageplaats;
    private javax.swing.JButton jButtonSaveStageplaats;
    private javax.swing.JComboBox<String> jComboBoxSitueert;
    private javax.swing.JComboBox<String> jComboBoxSpecialisatie;
    private javax.swing.JLabel jLabelAanmaakdatum;
    private javax.swing.JLabel jLabelGUIAanmaakdatum;
    private javax.swing.JLabel jLabelGUIAantalPlaatsen;
    private javax.swing.JLabel jLabelGUIBedrijf;
    private javax.swing.JLabel jLabelGUIBegeleiding;
    private javax.swing.JLabel jLabelGUIID;
    private javax.swing.JLabel jLabelGUILaatsteWijziging;
    private javax.swing.JLabel jLabelGUIOmschrijving;
    private javax.swing.JLabel jLabelGUIPeriode;
    private javax.swing.JLabel jLabelGUISitueert;
    private javax.swing.JLabel jLabelGUISpecialisatie;
    private javax.swing.JLabel jLabelGUITitel;
    private javax.swing.JLabel jLabelGUIVereisteKennis;
    private javax.swing.JLabel jLabelGUIVoorzieningen;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabellaatsteWijzing;
    private javax.swing.JList jListStageplaatsen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSlider jSliderAantalPlaatsen;
    private javax.swing.JTextArea jTextAreaBegeleiding;
    private javax.swing.JTextArea jTextAreaOmschrijving;
    private javax.swing.JTextArea jTextAreaVereisteKennis;
    private javax.swing.JTextArea jTextAreaVoorzieningen;
    private javax.swing.JTextField jTextFieldBedrijfsnaam;
    private javax.swing.JTextField jTextFieldPeriode;
    private javax.swing.JTextField jTextFieldTitel;
    // End of variables declaration//GEN-END:variables
}
